// packages/generators/src/cli/react-app-generator.ts
import { title } from "./common-generator.js";
import type { ReactVersionProfile } from "./generator-versions.js";

export function reactAppEntry(name: string, profile: ReactVersionProfile): string {
  const root = profile.major === 17
    ? `import type { ReactNode } from "react";
import { render, unmountComponentAtNode } from "react-dom";

function createRoot(container: Element) {
  return {
    render(element: ReactNode) {
      render(element, container);
    },
    unmount() {
      unmountComponentAtNode(container);
    }
  };
}`
    : 'import { createRoot } from "react-dom/client";';
  return `import { createElement } from "react";\n${root}\nimport { createMemoryRouter, RouterProvider } from "react-router-dom";\nimport { createRouterOptions, createRoutedApp } from "@atlas/sdk/react";\nimport { routes } from "./app/routes";\n\nexport default createRoutedApp({\n  createRoot,\n  createRouter: ({ context }) => createMemoryRouter(routes, createRouterOptions(context)),\n  createElement: (router) => createElement(RouterProvider, { router })\n});\n`;
}

export function reactSinglePageAppEntry(name: string, profile: ReactVersionProfile): string {
  const root = profile.major === 17
    ? `import type { ReactNode } from "react";
import { render, unmountComponentAtNode } from "react-dom";

function createRoot(container: Element) {
  return {
    render(element: ReactNode) {
      render(element, container);
    },
    unmount() {
      unmountComponentAtNode(container);
    }
  };
}`
    : 'import { createRoot } from "react-dom/client";';
  return `import { createElement } from "react";\n${root}\nimport { defineApp } from "@atlas/sdk/react";\nimport { App } from "./app/App";\n\nexport default defineApp({\n  createRoot,\n  createElement: () => createElement(App, { name: "${title(name)}" })\n});\n`;
}

export function reactAppApp(name: string): string {
  return `import { Link, Outlet } from "react-router-dom";
import "../styles.css";

export function App() {
  return (
    <section>
      <h1>${title(name)}</h1>
      <nav>
        <Link to="/">Home</Link>
        <Link to="details/42">Details</Link>
      </nav>
      <Outlet />
    </section>
  );
}
`;
}

export function reactSinglePageApp(name: string): string {
  return `import "../styles.css";

interface AppProps {
  name?: string;
}

export function App({ name = "${title(name)}" }: AppProps) {
  return (
    <section>
      <h1>{name}</h1>
      <p>Single-page Atlas app</p>
    </section>
  );
}
`;
}

export function reactAppHome(name: string): string {
  return `export function Home() {
  return <p>${title(name)} home</p>;
}
`;
}

export function reactAppDetails(): string {
  return `export function Details() {
  return <p>Routed details page</p>;
}
`;
}

export function reactAppRoutes(): string {
  return `import type { RouteObject } from "react-router-dom";
import { App } from "./App";
import { Details } from "./details/Details";
import { Home } from "./home/Home";

export const routes: RouteObject[] = [
  {
    path: "/",
    Component: App,
    children: [
      { index: true, Component: Home },
      { path: "details/:id", Component: Details }
    ]
  }
];
`;
}

export function appSourceReadme(entryFile: string, bundlerFile: string): string {
  return `# App source

Required Atlas wiring lives in \`${entryFile}\`, \`atlas.config.ts\`, and \`${bundlerFile}\`. Keep those files aligned with Atlas docs when changing platform wiring.

Main app component lives in \`src/app/App.tsx\`. Add screens under feature folders in \`src/app\`.

When inner routing is enabled, \`src/app/routes.tsx\` connects app screens to the router. Update it when adding routes.
`;
}

// packages/generators/src/cli/angular-app-generator.ts
import { angularRootSelector } from "./angular-names.js";
import { title } from "./common-generator.js";

export function angularAppEntry(name: string): string {
  const selector = angularRootSelector(name);
  return `import "zone.js";
import { LocationStrategy } from "@angular/common";
import { bootstrapApplication } from "@angular/platform-browser";
import { provideRouter } from "@angular/router";
import { createLocationStrategy, defineApp, provideAtlasAppContext, provideAtlasSdk } from "@atlas/sdk/angular";
import { routes } from "./app/routes";
import { AppComponent } from "./app/app.component";

export default defineApp(async ({ container, sdk, context }) => {
  const element = document.createElement("${selector}");
  const locationStrategy = createLocationStrategy(context);

  container.append(element);

  const app = await bootstrapApplication(AppComponent, {
    providers: [
      provideRouter(routes),
      provideAtlasAppContext(context),
      provideAtlasSdk(sdk),
      { provide: LocationStrategy, useValue: locationStrategy }
    ]
  });

  return {
    unmount() {
      app.destroy();
      locationStrategy.ngOnDestroy();
      element.remove();
    }
  };
});
`;
}

export function angularSinglePageAppEntry(name: string): string {
  const selector = angularRootSelector(name);
  return `import "zone.js";
import { bootstrapApplication } from "@angular/platform-browser";
import { defineApp, provideAtlasAppContext, provideAtlasSdk } from "@atlas/sdk/angular";
import { AppComponent } from "./app/app.component";

export default defineApp(async ({ container, sdk, context }) => {
  const element = document.createElement("${selector}");
  container.append(element);

  const app = await bootstrapApplication(AppComponent, {
    providers: [
      provideAtlasAppContext(context),
      provideAtlasSdk(sdk)
    ]
  });

  return {
    unmount() {
      app.destroy();
      element.remove();
    }
  };
});
`;
}

export function angularAppAppComponent(name: string): string {
  const selector = angularRootSelector(name);
  return `import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";

@Component({
  selector: "${selector}",
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: \`
    <section>
      <h1>${title(name)}</h1>
      <nav>
        <a routerLink="/">Home</a>
        <a routerLink="details/42">Details</a>
      </nav>
      <router-outlet />
    </section>
  \`
})
export class AppComponent {}
`;
}

export function angularSinglePageAppComponent(name: string): string {
  const selector = angularRootSelector(name);
  return `import { Component } from "@angular/core";

@Component({
  selector: "${selector}",
  standalone: true,
  template: \`
    <section>
      <h1>${title(name)}</h1>
      <p>Single-page Atlas app</p>
    </section>
  \`
})
export class AppComponent {}
`;
}

export function angularAppHomeComponent(name: string): string {
  return `import { Component } from "@angular/core";

@Component({
  selector: "atlas-app-home",
  standalone: true,
  template: \`<p>${title(name)} home</p>\`
})
export class HomeComponent {}
`;
}

export function angularAppDetailsComponent(): string {
  return `import { Component } from "@angular/core";

@Component({
  selector: "atlas-app-details",
  standalone: true,
  template: \`<p>Routed details page</p>\`
})
export class DetailsComponent {}
`;
}

export function angularAppRoutes(): string {
  return `import type { Routes } from "@angular/router";
import { DetailsComponent } from "./details/details.component";
import { HomeComponent } from "./home/home.component";

export const routes: Routes = [
  { path: "", component: HomeComponent },
  { path: "details/:id", component: DetailsComponent }
];
`;
}

export function appSourceReadme(): string {
  return `# App source

Required Atlas wiring lives in \`src/entry.ts\`, \`atlas.config.ts\`, and \`federation.config.js\`. Keep those files aligned with Atlas docs when changing platform wiring.

Main app component lives in \`src/app/app.component.ts\`. Add screens under feature folders in \`src/app\`.

When inner routing is enabled, \`src/app/routes.ts\` connects app screens to the router. Update it when adding routes.
`;
}
