// packages/generators/src/cli/angular-generator.ts
import { angularVersionProfile, atlasPackageRange, type AngularVersionProfile } from "./generator-versions.js";
import type { AtlasGeneratedFile, AtlasGeneratorOptions } from "./generator-types.js";
import { atlasConfig, atlasHostConfig, atlasHostStyles, json, title } from "./common-generator.js";

export function generateAngularHostFiles(options: AtlasGeneratorOptions): AtlasGeneratedFile[] {
  const { name } = options;
  const profile = angularVersionProfile(options);
  return [
    { path: "package.json", contents: json(angularPackage({ packageName: options.packageName ?? name, projectName: name, host: true, profile })) },
    { path: "angular.json", contents: json(angularWorkspace(name, true)) },
    { path: "tsconfig.json", contents: json(angularTsconfig()) },
    { path: "tsconfig.app.json", contents: json(angularAppTsconfig()) },
    { path: "tsconfig.atlas.json", contents: json(atlasConfigTsconfig()) },
    { path: "federation.config.js", contents: angularFederationConfig(name, true) },
    { path: "atlas.config.ts", contents: atlasHostConfig(options) },
    { path: "src/index.html", contents: angularIndex("Atlas Host", "<atlas-host-root></atlas-host-root>") },
    { path: "src/styles.css", contents: atlasHostStyles() },
    { path: "src/app/app.component.ts", contents: angularHostComponent() },
    { path: "src/main.ts", contents: angularHostMain() },
    { path: "src/bootstrap.ts", contents: angularHostBootstrap() }
  ];
}

export function generateAngularMicrofrontendFiles(options: AtlasGeneratorOptions): AtlasGeneratedFile[] {
  const { name } = options;
  const profile = angularVersionProfile(options);
  return [
    { path: "package.json", contents: json(angularPackage({ packageName: options.packageName ?? name, projectName: name, host: false, profile })) },
    { path: "angular.json", contents: json(angularWorkspace(name, false)) },
    { path: "tsconfig.json", contents: json(angularTsconfig()) },
    { path: "tsconfig.app.json", contents: json(angularAppTsconfig()) },
    { path: "tsconfig.atlas.json", contents: json(atlasConfigTsconfig()) },
    { path: "federation.config.js", contents: angularFederationConfig(name, false) },
    { path: "atlas.config.ts", contents: atlasConfig(options, false) },
    { path: "src/index.html", contents: angularIndex(title(name), "<div>Atlas microfrontend assets</div>") },
    { path: "src/styles.css", contents: "" },
    { path: "src/assets/.gitkeep", contents: "" },
    { path: "src/main.ts", contents: `import { initFederation } from "@angular-architects/native-federation";\n\nvoid initFederation();\n` },
    { path: "src/app/app.component.ts", contents: angularMicrofrontendComponent(name) },
    { path: "src/entry.ts", contents: angularMicrofrontendEntry(name) },
    { path: "src/exported-components/README.md", contents: `# Exported widgets\n\nCreate \`<widget-id>/index.ts\`; Atlas exposes it automatically. Consumers declare \`owner-mf/widget-id\` in \`uses\`.\n` }
  ];
}

interface AngularPackageOptions {
  packageName: string;
  projectName: string;
  host: boolean;
  profile: AngularVersionProfile;
}

function angularPackage(options: AngularPackageOptions): unknown {
  const { packageName, projectName, host, profile } = options;
  const angular = profile.version;
  return {
    name: packageName,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: host ? `atlas runtime-config ${projectName} && ng serve ${projectName}` : `ng serve ${projectName}`,
      "atlas:config": "tsc -p tsconfig.atlas.json",
      build: host ? `atlas runtime-config ${projectName} && ng build` : "tsc -p tsconfig.atlas.json && ng build",
      ...(host ? {} : { "atlas:build": `atlas build ${projectName}` })
    },
    dependencies: {
      "@angular/animations": angular,
      "@angular/common": angular,
      "@angular/compiler": angular,
      "@angular/core": angular,
      "@angular/platform-browser": angular,
      "@angular/router": angular,
      "@angular-architects/native-federation": `^${profile.major}.0.0`,
      "@atlas/schema": atlasPackageRange(),
      "@atlas/sdk": atlasPackageRange(),
      ...(host ? { "@atlas/runtime": atlasPackageRange() } : {}),
      "es-module-shims": "^2.7.0",
      rxjs: "^7.8.0",
      tslib: "^2.8.0",
      "zone.js": profile.zone
    },
    devDependencies: {
      "@angular-devkit/build-angular": angular,
      "@angular/cli": angular,
      "@angular/compiler-cli": angular,
      typescript: profile.typescript
    }
  };
}

function angularIndex(pageTitle: string, body: string): string {
  return `<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <title>${pageTitle}</title>\n  <base href="/">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n</head>\n<body>\n  ${body}\n</body>\n</html>\n`;
}

function angularWorkspace(name: string, host: boolean): unknown {
  return {
    version: 1,
    projects: {
      [name]: {
        projectType: "application", root: "", sourceRoot: "src",
        architect: {
          build: { builder: "@angular-architects/native-federation:build", options: { target: `${name}:esbuild:production` }, configurations: { development: { target: `${name}:esbuild:development`, dev: true } } },
          serve: { builder: "@angular-architects/native-federation:build", options: { target: `${name}:serve-original:development`, dev: true, port: host ? 4200 : 4201 } },
          esbuild: {
            builder: "@angular-devkit/build-angular:application",
            options: { outputPath: `dist/${name}`, index: "src/index.html", browser: "src/main.ts", polyfills: ["zone.js", "es-module-shims"], tsConfig: "tsconfig.app.json", assets: [{ glob: "**/*", input: "public" }, { glob: "**/*", input: "src/assets", output: "assets" }], styles: ["src/styles.css"] },
            configurations: { production: { outputHashing: "all" }, development: { optimization: false, sourceMap: true } }
          },
          "serve-original": { builder: "@angular-devkit/build-angular:dev-server", configurations: { production: { buildTarget: `${name}:esbuild:production` }, development: { buildTarget: `${name}:esbuild:development` } }, defaultConfiguration: "development" }
        }
      }
    }
  };
}

function angularTsconfig(): unknown {
  return { compilerOptions: { target: "ES2022", module: "ES2022", moduleResolution: "bundler", strict: true, experimentalDecorators: true, useDefineForClassFields: false, lib: ["ES2022", "DOM"], skipLibCheck: true }, angularCompilerOptions: { strictTemplates: true, strictInjectionParameters: true } };
}

function angularAppTsconfig(): unknown {
  return { extends: "./tsconfig.json", compilerOptions: { outDir: "./out-tsc/app" }, files: ["src/main.ts"], include: ["src/**/*.ts"] };
}

function atlasConfigTsconfig(): unknown {
  return { extends: "./tsconfig.json", compilerOptions: { outDir: ".atlas", module: "Node16", moduleResolution: "Node16" }, files: ["atlas.config.ts"] };
}

function angularFederationConfig(name: string, host: boolean): string {
  return `// Generated by Atlas for @angular-architects/native-federation.\n// Edit atlas.config.ts and application source; do not hand-edit this compatibility file.\n// Native Federation requires this exact filename next to the Angular tsconfig.\nconst { readdirSync, existsSync } = require("node:fs");\nconst { join } = require("node:path");\nconst { withNativeFederation } = require("@angular-architects/native-federation/config");\n\nconst componentsRoot = join(__dirname, "src/exported-components");\nconst componentExposes = existsSync(componentsRoot)\n  ? Object.fromEntries(readdirSync(componentsRoot, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => [\`./components/\${entry.name}\`, \`./src/exported-components/\${entry.name}/index.ts\`]))\n  : {};\n\nmodule.exports = withNativeFederation({\n  name: "${remoteName(name)}",\n  exposes: ${host ? "{}" : `{ "./entry": "./src/entry.ts", ...componentExposes }`},\n  // Product dependencies stay inside this build so hosts never impose their versions.\n  shared: {},\n  skip: ["rxjs/ajax", "rxjs/fetch", "rxjs/testing", "rxjs/webSocket"]\n});\n`;
}

function angularHostComponent(): string {
  return `import { Component } from "@angular/core";\nimport { RouterOutlet } from "@angular/router";\n\n@Component({ selector: "atlas-router-anchor", standalone: true, template: "" })\nexport class AtlasRouterAnchorComponent {}\n\n@Component({ selector: "atlas-host-root", standalone: true, imports: [RouterOutlet], template: \`<div data-atlas-host-status></div><header><strong>Atlas</strong><div data-atlas-slot="header"></div></header><nav data-atlas-navigation aria-label="Application"></nav><main data-atlas-route-outlet></main><router-outlet hidden />\` })\nexport class AppComponent {}\n`;
}

function angularHostMain(): string {
  return `import { initFederation } from "@angular-architects/native-federation";\n\nvoid initFederation()\n  .then(() => import("./bootstrap"))\n  .then(({ bootstrap }) => bootstrap())\n  .catch((error) => console.error("Atlas host failed to start", error));\n`;
}

function angularHostBootstrap(): string {
  return `import { Location } from "@angular/common";\nimport { bootstrapApplication } from "@angular/platform-browser";\nimport { provideRouter, Router } from "@angular/router";\nimport { initFederation, loadRemoteModule } from "@angular-architects/native-federation";\nimport { startHost } from "@atlas/runtime/angular";\nimport { createFetchAtlasHttpClient, type AtlasHostData } from "@atlas/sdk";\nimport atlasConfig from "../atlas.config";\nimport { AppComponent, AtlasRouterAnchorComponent } from "./app/app.component";\n\nexport async function bootstrap(): Promise<void> {\n  const app = await bootstrapApplication(AppComponent, { providers: [provideRouter([{ path: "**", component: AtlasRouterAnchorComponent }])] });\n  const hostData: AtlasHostData = { hostId: atlasConfig.id, name: atlasConfig.name ?? atlasConfig.id };\n  await startHost({\n    router: app.injector.get(Router),\n    location: app.injector.get(Location),\n    federation: { initFederation, loadRemoteModule },\n    showToast: (toast) => console.info("[Atlas toast]", toast.title),\n    getCurrentUser: async () => ({ id: "local-user", displayName: "Local Developer" }),\n    hostData,\n    httpClient: createFetchAtlasHttpClient(fetch)\n  });\n}\n`;
}

function angularMicrofrontendEntry(name: string): string {
  const selector = `atlas-${name.replace(/[^a-zA-Z0-9-]/g, "-")}-root`;
  return `import "zone.js";
import { LocationStrategy } from "@angular/common";
import { bootstrapApplication } from "@angular/platform-browser";
import { provideRouter } from "@angular/router";
import { createLocationStrategy, defineMicrofrontend, provideAtlasMfContext, provideAtlasSdk } from "@atlas/sdk/angular";
import { AppComponent, routes } from "./app/app.component";

export default defineMicrofrontend(async ({ container, sdk, context }) => {
  const element = document.createElement("${selector}");
  const locationStrategy = createLocationStrategy(context);

  container.append(element);

  const app = await bootstrapApplication(AppComponent, {
    providers: [
      provideRouter(routes),
      provideAtlasMfContext(context),
      provideAtlasSdk(sdk),
      { provide: LocationStrategy, useValue: locationStrategy }
    ]
  });

  return {
    unmount() {
      app.destroy();
      locationStrategy.ngOnDestroy();
      element.remove();
    }
  };
});
`;
}

function angularMicrofrontendComponent(name: string): string {
  const selector = `atlas-${name.replace(/[^a-zA-Z0-9-]/g, "-")}-root`;
  return `import { Component } from "@angular/core";
import { RouterLink, RouterOutlet, type Routes } from "@angular/router";

@Component({
  selector: "atlas-mf-home",
  standalone: true,
  template: \`<p>${title(name)} home</p>\`
})
class HomeComponent {}

@Component({
  selector: "atlas-mf-details",
  standalone: true,
  template: \`<p>Routed details page</p>\`
})
class DetailsComponent {}

@Component({
  selector: "${selector}",
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: \`
    <section>
      <h1>${title(name)}</h1>
      <nav>
        <a routerLink="/">Home</a>
        <a routerLink="details/42">Details</a>
      </nav>
      <router-outlet />
    </section>
  \`
})
export class AppComponent {}

export const routes: Routes = [
  { path: "", component: HomeComponent },
  { path: "details/:id", component: DetailsComponent }
];
`;
}

function remoteName(name: string): string {
  return `atlas_${name.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

// packages/generators/src/cli/react-generator.ts
import { reactVersionProfile, atlasPackageRange, type ReactVersionProfile } from "./generator-versions.js";
import type { AtlasGeneratedFile, AtlasGeneratorOptions } from "./generator-types.js";
import { atlasConfig, atlasHostConfig, atlasHostStyles, json, title } from "./common-generator.js";

const REACT_COMPILER_VERSION = "1.0.0";

export function generateReactHostFiles(options: AtlasGeneratorOptions): AtlasGeneratedFile[] {
  const { name } = options;
  const profile = reactVersionProfile(options);
  return [
    { path: "package.json", contents: json(reactPackage({ packageName: options.packageName ?? name, projectName: name, host: true, profile })) },
    { path: "tsconfig.json", contents: json(reactTsconfig()) },
    { path: "tsconfig.atlas.json", contents: json(reactAtlasTsconfig()) },
    { path: "vite.config.ts", contents: reactHostViteConfig(profile.compilerTarget) },
    { path: "atlas.config.ts", contents: atlasHostConfig(options) },
    { path: "public/remoteEntry.json", contents: json({ name: remoteName(name), exposes: [], shared: [] }) },
    { path: "index.html", contents: reactIndex("Atlas React Host") },
    { path: "src/styles.css", contents: atlasHostStyles() },
    { path: "src/main.tsx", contents: reactHostMain(profile) }
  ];
}

export function generateReactMicrofrontendFiles(options: AtlasGeneratorOptions): AtlasGeneratedFile[] {
  const { name } = options;
  const profile = reactVersionProfile(options);
  return [
    { path: "package.json", contents: json(reactPackage({ packageName: options.packageName ?? name, projectName: name, host: false, profile })) },
    { path: "tsconfig.json", contents: json(reactTsconfig()) },
    { path: "tsconfig.atlas.json", contents: json(reactAtlasTsconfig()) },
    { path: "vite.config.ts", contents: reactMicrofrontendViteConfig(name, profile.compilerTarget) },
    { path: "atlas.config.ts", contents: atlasConfig(options, false) },
    { path: "index.html", contents: reactIndex(`${title(name)} assets`) },
    { path: "src/styles.css", contents: "" },
    { path: "src/entry.tsx", contents: reactMicrofrontendEntry(name, profile) },
    { path: "src/exported-components/README.md", contents: `# Exported widgets\n\nCreate \`<widget-id>/index.tsx\`; Atlas exposes it automatically through Native Federation. Consumers declare \`owner-mf/widget-id\` in \`uses\`.\n` }
  ];
}

interface ReactPackageOptions {
  packageName: string;
  projectName: string;
  host: boolean;
  profile: ReactVersionProfile;
}

function reactPackage(options: ReactPackageOptions): unknown {
  const { packageName, projectName, host, profile } = options;
  return {
    name: packageName,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      dev: host ? `atlas runtime-config ${projectName} && vite --host 0.0.0.0` : "vite --host 0.0.0.0",
      "atlas:config": "tsc -p tsconfig.atlas.json",
      build: host ? `atlas runtime-config ${projectName} && tsc -b && vite build` : "tsc -p tsconfig.atlas.json && tsc -b && vite build",
      ...(host ? {} : { "atlas:build": `atlas build ${projectName}` })
    },
    dependencies: {
      "@atlas/schema": atlasPackageRange(),
      "@atlas/sdk": atlasPackageRange(),
      ...(host ? { "@atlas/runtime": atlasPackageRange() } : {}),
      "@softarc/native-federation-runtime": "^3.5.5",
      "es-module-shims": "^2.7.0",
      react: profile.version,
      "react-dom": profile.version,
      "react-router-dom": profile.routerVersion,
      ...(profile.major < 19 ? { "react-compiler-runtime": REACT_COMPILER_VERSION } : {})
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      "@types/react": `^${profile.major}.0.0`,
      "@types/react-dom": `^${profile.major}.0.0`,
      "@vitejs/plugin-react": "^5.0.4",
      "babel-plugin-react-compiler": REACT_COMPILER_VERSION,
      typescript: "~5.9.0",
      vite: "^7.3.6"
    }
  };
}

function reactTsconfig(): unknown {
  return {
    compilerOptions: {
      target: "ES2022", useDefineForClassFields: true, lib: ["ES2022", "DOM", "DOM.Iterable"],
      module: "ESNext", moduleResolution: "bundler", jsx: "react-jsx", strict: true,
      noEmit: true, skipLibCheck: true, allowImportingTsExtensions: true, types: ["vite/client"]
    },
    include: ["src", "vite.config.ts"]
  };
}

function reactAtlasTsconfig(): unknown {
  return { extends: "./tsconfig.json", compilerOptions: { noEmit: false, allowImportingTsExtensions: false, outDir: ".atlas", module: "Node16", moduleResolution: "Node16", types: ["node"] }, files: ["atlas.config.ts"], include: [] };
}

function reactHostViteConfig(compilerTarget: string): string {
  return `import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({ plugins: [react({ babel: { plugins: [["babel-plugin-react-compiler", { target: "${compilerTarget}", panicThreshold: "none" }]] } })], server: { port: 4200 }, build: { target: "esnext" } });\n`;
}

function reactMicrofrontendViteConfig(name: string, compilerTarget: string): string {
  return `import { existsSync, readdirSync, writeFileSync } from "node:fs";\nimport { resolve } from "node:path";\nimport { defineConfig, type Plugin } from "vite";\nimport react from "@vitejs/plugin-react";\n\nconst componentsRoot = resolve(__dirname, "src/exported-components");\nconst componentIds = existsSync(componentsRoot) ? readdirSync(componentsRoot, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => entry.name) : [];\nconst exposes = [{ key: "./entry", outFileName: "entry.js" }, ...componentIds.map((id) => ({ key: \`./components/\${id}\`, outFileName: \`components/\${id}.js\` }))];\n\nfunction atlasFederationMetadata(): Plugin {\n  const metadata = { name: "${remoteName(name)}", exposes, shared: [] };\n  return {\n    name: "atlas-native-federation-metadata",\n    configureServer(server) {\n      server.middlewares.use("/remoteEntry.json", (_request, response) => { response.setHeader("content-type", "application/json"); response.setHeader("access-control-allow-origin", "*"); response.end(JSON.stringify({ ...metadata, exposes: [{ key: "./entry", outFileName: "src/entry.tsx", dev: { entryPoint: "src/entry.tsx" } }, ...componentIds.map((id) => ({ key: \`./components/\${id}\`, outFileName: \`src/exported-components/\${id}/index.tsx\`, dev: { entryPoint: \`src/exported-components/\${id}/index.tsx\` } }))] })); });\n    },\n    closeBundle() { writeFileSync(resolve(__dirname, "dist/remoteEntry.json"), JSON.stringify(metadata, null, 2)); }\n  };\n}\n\nexport default defineConfig({\n  base: "./",\n  plugins: [react({ babel: { plugins: [["babel-plugin-react-compiler", { target: "${compilerTarget}", panicThreshold: "none" }]] } }), atlasFederationMetadata()],\n  server: { port: 4201, cors: true },\n  build: {\n    target: "esnext",\n    rollupOptions: {\n      input: Object.fromEntries([["entry", resolve(__dirname, "src/entry.tsx")], ...componentIds.map((id) => [\`components/\${id}\`, resolve(componentsRoot, id, "index.tsx")])]),\n      output: { entryFileNames: "[name].js", chunkFileNames: "chunks/[name]-[hash].js", assetFileNames: "assets/[name]-[hash][extname]" },\n      preserveEntrySignatures: "exports-only"\n    }\n  }\n});\n`;
}

function reactIndex(pageTitle: string): string {
  return `<!doctype html>\n<html lang="en">\n<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${pageTitle}</title><script type="esms-options">{ "shimMode": true, "mapOverrides": true }</script></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n`;
}

function reactHostMain(profile: ReactVersionProfile): string {
  const rootImport = profile.major === 17
    ? 'import { render, unmountComponentAtNode } from "react-dom";'
    : 'import { flushSync } from "react-dom";\nimport { createRoot } from "react-dom/client";';
  const mount = profile.major === 17
    ? "render(<StrictMode><RouterProvider router={router} /></StrictMode>, root);\nif (import.meta.hot) import.meta.hot.dispose(() => unmountComponentAtNode(root));"
    : "const reactRoot = createRoot(root);\nflushSync(() => reactRoot.render(<StrictMode><RouterProvider router={router} /></StrictMode>));\nif (import.meta.hot) import.meta.hot.dispose(() => reactRoot.unmount());";
  return `import "es-module-shims";\nimport { StrictMode } from "react";\n${rootImport}\nimport { createBrowserRouter, RouterProvider } from "react-router-dom";\nimport { initFederation, loadRemoteModule } from "@softarc/native-federation-runtime";\nimport { startHost } from "@atlas/runtime/react";\nimport { createFetchAtlasHttpClient, type AtlasHostData } from "@atlas/sdk";\nimport atlasConfig from "../atlas.config";\nimport "./styles.css";\n\nfunction Shell() { return <><div data-atlas-host-status /><header><strong>Atlas</strong><div data-atlas-slot="header" /></header><nav data-atlas-navigation aria-label="Application" /><main data-atlas-route-outlet /></>; }\nconst router = createBrowserRouter([{ path: "*", Component: Shell }]);\nconst root = document.getElementById("root");\nif (!root) throw new Error("Atlas React host root was not found.");\nconst hostData: AtlasHostData = { hostId: atlasConfig.id, name: atlasConfig.name ?? atlasConfig.id };\n${mount}\nvoid startHost({ router, federation: { initFederation, loadRemoteModule }, showToast: (toast) => console.info("[Atlas toast]", toast.title), getCurrentUser: async () => ({ id: "local-user", displayName: "Local Developer" }), hostData, httpClient: createFetchAtlasHttpClient(fetch) }).catch((error) => console.error("Atlas host failed to start", error));\n`;
}

function reactMicrofrontendEntry(name: string, profile: ReactVersionProfile): string {
  const root = profile.major === 17
    ? 'import type { ReactNode } from "react";\nimport { render, unmountComponentAtNode } from "react-dom";\n\nfunction createRoot(container: Element) {\n  return { render(element: ReactNode) { render(element, container); }, unmount() { unmountComponentAtNode(container); } };\n}'
    : 'import { createRoot } from "react-dom/client";';
  return `import { createElement } from "react";\n${root}\nimport { createMemoryRouter, Link, Outlet, RouterProvider } from "react-router-dom";\nimport { createRouterOptions, createRoutedMicrofrontend, useAtlasSdk } from "@atlas/sdk/react";\nimport "./styles.css";\n\nif (import.meta.hot) await import("@vitejs/plugin-react/preamble");\n\nfunction Layout() { const atlas = useAtlasSdk(); return <section><h1>${title(name)}</h1><button type="button" onClick={() => atlas.toast.open({ title: "${title(name)} is ready" })}>Show toast</button><nav><Link to="/">Home</Link> <Link to="details/42">Details</Link></nav><Outlet /></section>; }\nfunction Home() { return <p>${title(name)} home</p>; }\nfunction Details() { return <p>Routed details page</p>; }\nconst routes = [{ path: "/", Component: Layout, children: [{ index: true, Component: Home }, { path: "details/:id", Component: Details }] }];\n\nexport default createRoutedMicrofrontend({\n  createRoot,\n  createRouter: ({ context }) => createMemoryRouter(routes, createRouterOptions(context)),\n  createElement: (router) => createElement(RouterProvider, { router })\n});\n`;
}

function remoteName(name: string): string {
  return `atlas_${name.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}
