// packages/generators/src/cli/angular-host-generator.ts
export function angularHostComponent(): string {
  return `import { Component } from "@angular/core";
import { RouterOutlet } from "@angular/router";

@Component({
  selector: "atlas-host-root",
  standalone: true,
  imports: [RouterOutlet],
  template: \`
    <div data-atlas-host-status></div>
    <header>
      <strong>Atlas</strong>
      <div data-atlas-slot="header"></div>
    </header>
    <nav data-atlas-navigation aria-label="Application"></nav>
    <main data-atlas-route-outlet></main>
    <router-outlet hidden />
  \`
})
export class AppComponent {}
`;
}

export function angularHostMain(): string {
  return `import { initFederation } from "@atlas/sdk/federation";

void initFederation()
  .then(() => import("./bootstrap"))
  .then(({ bootstrap }) => bootstrap())
  .catch((cause) => console.error("Atlas host failed to start.", {
    message: \`Atlas could not initialize Native Federation: \${cause instanceof Error ? cause.message : String(cause)}\`,
    suggestedActions: [
      "Verify the deployed remote-entry URLs, CORS headers, and federation metadata.",
      "Correct the host or app deployment, then reload the page."
    ],
    code: "ATLAS_FEDERATION_INIT_FAILED",
    cause
  }));
`;
}

export function angularHostDefaultRouteComponent(): string {
  return `import { Component } from "@angular/core";

@Component({ selector: "atlas-host-default-route", standalone: true, template: "" })
export class AtlasHostDefaultRouteComponent {}
`;
}

export function angularHostBootstrap(): string {
  return `import { Location } from "@angular/common";
import { bootstrapApplication } from "@angular/platform-browser";
import { provideRouter, Router } from "@angular/router";
import { initFederation, loadRemoteModule } from "@atlas/sdk/federation";
import type { AtlasHostClientEntry } from "@atlas/sdk/lifecycle";
import { startHost } from "@atlas/runtime/angular";
import atlasConfig from "../atlas.config";
import { AppComponent } from "./app/app.component";
import { AtlasHostDefaultRouteComponent } from "./app/atlas-host-default-route.component";

type HostMountRequest = Parameters<AtlasHostClientEntry["mount"]>[0];

export async function bootstrap(request?: HostMountRequest) {
  const root = request ? document.createElement("atlas-host-root") : undefined;
  if (root && request) request.container.append(root);
  const app = await bootstrapApplication(AppComponent, {
    providers: [provideRouter([{ path: "**", component: AtlasHostDefaultRouteComponent }])]
  });

  const runtime = await startHost({
    router: app.injector.get(Router),
    location: app.injector.get(Location),
    federation: { initFederation, loadRemoteModule },
    hostData: { hostId: atlasConfig.id, name: atlasConfig.name },
    ...(request ? { runtimeConfig: request.runtimeConfig, catalog: request.catalog } : {})
  });
  return {
    async unmount() {
      await runtime.stop();
      app.destroy();
      root?.remove();
    }
  };
}
`;
}

export function angularHostEntry(): string {
  return `import "zone.js";
import type { AtlasHostClientEntry } from "@atlas/sdk/lifecycle";
import { bootstrap } from "./bootstrap";

export const mount: AtlasHostClientEntry["mount"] = (request) => bootstrap(request);
`;
}

// packages/generators/src/cli/react-host-generator.ts
import { title } from "./common-generator.js";
import type { ReactVersionProfile } from "./generator-versions.js";

export function reactHostMain(name: string, profile: ReactVersionProfile): string {
  const providerName = reactHostProviderName(name);
  const rootImport = profile.major === 17
    ? 'import { render } from "react-dom";'
    : 'import { flushSync } from "react-dom";\nimport { createRoot } from "react-dom/client";';
  const mount = profile.major === 17
    ? `render(
  <StrictMode>
    <${providerName}>
      <RouterProvider router={router} />
    </${providerName}>
  </StrictMode>,
  root
);`
    : `const reactRoot = createRoot(root);
flushSync(() =>
  reactRoot.render(
    <StrictMode>
      <${providerName}>
        <RouterProvider router={router} />
      </${providerName}>
    </StrictMode>
  )
);`;
  return `import "es-module-shims";
import { StrictMode } from "react";
${rootImport}
import { RouterProvider } from "react-router-dom";
import { AtlasError } from "@atlas/schema";
import { ${providerName}, router } from "./${providerName}";
import "./styles.css";

const root = document.getElementById("root");
if (!root) {
  throw new AtlasError("Atlas cannot start the React host because element #root is missing.", {
    suggestedActions: [
      'Add <div id="root"></div> to the host index.html.',
      "Rebuild and redeploy the host, then reload the page."
    ],
    code: "ATLAS_REACT_HOST_ROOT_MISSING",
    surface: "browser"
  });
}

${mount}
`;
}

export function reactHostProvider(name: string): string {
  const providerName = reactHostProviderName(name);
  return `import type { PropsWithChildren } from "react";
import type { AtlasDeploymentCatalog, AtlasHostRuntimeConfig } from "@atlas/schema";
import { createBrowserRouter } from "react-router-dom";
import { initFederation, loadRemoteModule } from "@atlas/sdk/federation";
import { AtlasHostProvider } from "@atlas/runtime/react";
import atlasConfig from "../atlas.config";
import { HostLayout } from "./app/HostLayout";

export const router = createBrowserRouter([{ path: "*", Component: HostLayout }]);

interface HostProviderProps extends PropsWithChildren {
  runtimeConfig?: AtlasHostRuntimeConfig;
  catalog?: AtlasDeploymentCatalog;
}

export function ${providerName}({ children, runtimeConfig, catalog }: HostProviderProps) {
  return (
    <AtlasHostProvider
      hostId={atlasConfig.id}
      options={{
        router,
        federation: { initFederation, loadRemoteModule },
        hostData: { hostId: atlasConfig.id, name: atlasConfig.name },
        ...(runtimeConfig ? { runtimeConfig } : {}),
        ...(catalog ? { catalog } : {})
      }}
    >
      {children}
    </AtlasHostProvider>
  );
}
`;
}

export function reactHostEntry(name: string, profile: ReactVersionProfile): string {
  const providerName = reactHostProviderName(name);
  const imports = profile.major === 17
    ? 'import { render, unmountComponentAtNode } from "react-dom";'
    : 'import { flushSync } from "react-dom";\nimport { createRoot } from "react-dom/client";';
  const renderHost = profile.major === 17
    ? `render(element, request.container);\n  return { unmount: () => unmountComponentAtNode(request.container) };`
    : `const root = createRoot(request.container);\n  flushSync(() => root.render(element));\n  return { unmount: () => root.unmount() };`;
  return `import { StrictMode } from "react";
${imports}
import { RouterProvider } from "react-router-dom";
import type { AtlasHostClientEntry } from "@atlas/sdk/lifecycle";
import { ${providerName}, router } from "./${providerName}";
import "./styles.css";

export const mount: AtlasHostClientEntry["mount"] = (request) => {
  const element = (
    <StrictMode>
      <${providerName} runtimeConfig={request.runtimeConfig} catalog={request.catalog}>
        <RouterProvider router={router} />
      </${providerName}>
    </StrictMode>
  );
  ${renderHost}
};
`;
}

export function reactHostLayout(): string {
  return `export function HostLayout() {
  return (
    <>
      <div data-atlas-host-status />
      <header>
        <strong>Atlas</strong>
        <div data-atlas-slot="header" />
      </header>
      <nav data-atlas-navigation aria-label="Application" />
      <main data-atlas-route-outlet />
    </>
  );
}
`;
}

export function reactHostProviderName(name: string): string {
  const hostName = title(name).replaceAll(" ", "");
  const componentName = /^[A-Za-z_$]/.test(hostName) ? hostName : `Host${hostName}`;
  return `${componentName}AtlasProvider`;
}
