// packages/sdk/src/angular-app.ts
import { createComponent, type Type } from "@angular/core";
import type { AtlasExportedWidgetEntry, AtlasExportedWidgetMountRequest, AtlasAppEntry, AtlasAppMountRequest, AtlasAppMountResult } from "./lifecycle.js";

export interface AppBootstrap {
  (request: AtlasAppMountRequest): void | AtlasAppMountResult | Promise<void | AtlasAppMountResult>;
}

export function defineApp(bootstrap: AppBootstrap): AtlasAppEntry {
  return {
    mount(request) {
      return bootstrap(request);
    }
  };
}

export function defineExportedWidget<TProps extends object>(
  bootstrap: (request: AtlasExportedWidgetMountRequest<TProps>) => void | AtlasAppMountResult | Promise<void | AtlasAppMountResult>
): AtlasExportedWidgetEntry<TProps> {
  return { mount: bootstrap };
}

export function createExportedWidget<TProps extends object>(
  componentType: Type<unknown>
): AtlasExportedWidgetEntry<TProps> {
  return defineExportedWidget(async ({ container, props }) => {
    const { createApplication } = await import("@angular/platform-browser");
    const application = await createApplication();
    const component = createComponent(componentType, {
      environmentInjector: application.injector,
      hostElement: container
    });
    application.attachView(component.hostView);
    for (const [name, value] of Object.entries(props)) component.setInput(name, value);
    component.changeDetectorRef.detectChanges();

    return {
      setInputs(inputs: TProps) {
        for (const [name, value] of Object.entries(inputs)) component.setInput(name, value);
        component.changeDetectorRef.detectChanges();
      },
      unmount() {
        application.detachView(component.hostView);
        component.destroy();
        application.destroy();
      }
    };
  });
}

// packages/sdk/src/react-app.ts
import { createElement as createReactElement, type ReactNode } from "react";
import type { AtlasExportedWidgetEntry, AtlasExportedWidgetMountRequest, AtlasExportedWidgetMountResult, AtlasAppEntry, AtlasAppMountRequest, AtlasAppMountResult } from "./lifecycle.js";
import { AtlasRuntimeContext, AtlasSdkContext } from "./react-context.js";
import { connectRouter, type AppRouterLike } from "./react-router.js";

export interface RootAdapter {
  render(element: unknown): void;
  unmount(): void;
}

export interface AppOptions {
  createRoot(container: HTMLElement): RootAdapter;
  createElement(request: AtlasAppMountRequest): unknown;
}

export function defineApp(options: AppOptions): AtlasAppEntry {
  return {
    mount(request): AtlasAppMountResult {
      const root = options.createRoot(request.container);
      root.render(renderWithAtlasProviders(request, options.createElement(request)));
      return {
        unmount() {
          root.unmount();
        }
      };
    }
  };
}

export function createRoutedApp<TRouter extends AppRouterLike>(options: {
  createRoot(container: HTMLElement): RootAdapter;
  createRouter(request: AtlasAppMountRequest): TRouter;
  createElement(router: TRouter, request: AtlasAppMountRequest): unknown;
}): AtlasAppEntry {
  return {
    mount(request): AtlasAppMountResult {
      const root = options.createRoot(request.container);
      const router = options.createRouter(request);
      const disconnect = connectRouter(router, request.context);

      root.render(renderWithAtlasProviders(request, options.createElement(router, request)));

      return {
        unmount() {
          disconnect();
          router.dispose?.();
          root.unmount();
        }
      };
    }
  };
}

export function defineExportedWidget<TProps extends object>(options: {
  createRoot(container: HTMLElement): RootAdapter;
  createElement(request: AtlasExportedWidgetMountRequest<TProps>): unknown;
}): AtlasExportedWidgetEntry<TProps> {
  return {
    mount(request): AtlasExportedWidgetMountResult<TProps> {
      const root = options.createRoot(request.container);
      root.render(options.createElement(request));
      return {
        setInputs(inputs) {
          root.render(options.createElement({ ...request, props: inputs }));
        },
        unmount: () => root.unmount()
      };
    }
  };
}

function renderWithAtlasProviders(request: AtlasAppMountRequest, element: unknown): ReactNode {
  return createReactElement(
    AtlasSdkContext.Provider,
    { value: request.sdk },
    createReactElement(AtlasRuntimeContext.Provider, { value: request.context }, element as ReactNode)
  );
}
