// packages/sdk/src/react/react-widget/react-atlas-sdk.driver.tsx
import { faker } from '@faker-js/faker';
import type { ComponentType } from 'react';
import {
  connectAtlasWidgetResolver,
  createAtlasSdk,
} from '../../core/sdk-factory/index.js';
import {
  anAppContext,
  anAppManifest,
} from '../../testkit/app-context.testkit.js';
import { aMemoryNavigation } from '../../testkit/navigation.testkit.js';
import { createReactAtlasSdk } from './react-atlas-sdk.js';
import type { ReactAtlasSdk } from './react-widget.types.js';

export class ReactAtlasSdkDriver {
  private readonly sdk = createAtlasSdk({
    hostId: faker.string.uuid(),
    navigation: aMemoryNavigation(),
  });
  private reactSdk: ReactAtlasSdk = createReactAtlasSdk(this.sdk);

  constructor() {
    connectAtlasWidgetResolver(this.sdk, (widgetId) => ({
      id: widgetId,
      name: faker.commerce.productName(),
      mount: async () => ({ unmount: async () => undefined }),
    }));
  }

  readonly given = {
    remoteEntryUrl: (remoteEntryUrl: string): this => {
      this.reactSdk = createReactAtlasSdk(
        this.sdk,
        anAppContext({ manifest: anAppManifest({ remoteEntryUrl }) }),
      );

      return this;
    },
  };

  readonly get = {
    widget: (widgetId: string): ComponentType<object> =>
      this.reactSdk.getWidget<object>(widgetId),
    reactSdk: (): ReactAtlasSdk => this.reactSdk,
  };
}

// packages/sdk/src/angular/angular-widget/angular-atlas-sdk.driver.ts
import '@angular/compiler';
import { faker } from '@faker-js/faker';
import {
  signal,
  type ApplicationRef,
  type EnvironmentInjector,
} from '@angular/core';
import {
  connectAtlasWidgetResolver,
  createAtlasSdk,
} from '../../core/sdk-factory/index.js';
import { aMemoryNavigation } from '../../testkit/navigation.testkit.js';
import { createAngularAtlasSdk } from './angular-atlas-sdk.js';
import type { AngularAtlasSdk } from './angular-widget.types.js';

interface WidgetInputs {
  readonly count: number;
}

export class AngularAtlasSdkDriver {
  private readonly sdk = createAtlasSdk({
    hostId: faker.string.uuid(),
    navigation: aMemoryNavigation(),
  });
  private readonly angularSdk: AngularAtlasSdk = createAngularAtlasSdk({
    sdk: this.sdk,
    applicationRef: Object.create(null) as ApplicationRef,
    environmentInjector: Object.create(null) as EnvironmentInjector,
    hostData: signal(this.sdk.hostData).asReadonly(),
  });

  constructor() {
    connectAtlasWidgetResolver(this.sdk, (widgetId) => ({
      id: widgetId,
      name: faker.commerce.productName(),
      mount: async () => ({ unmount: async () => undefined }),
    }));
  }

  readonly get = {
    binding: (widgetId: string, inputs: WidgetInputs) =>
      this.angularSdk.getWidget<WidgetInputs>(widgetId, { inputs }),
    hostData: () => this.angularSdk.hostData(),
    sdkHostData: () => this.sdk.hostData,
  };
}
