// examples/hosts/demo-angular-host/src/bootstrap.ts
import { Location } from "@angular/common";
import { Component } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import { provideRouter, Router } from "@angular/router";
import { initFederation, loadRemoteModule } from "@atlas/sdk/federation";
import { startHost } from "@atlas/runtime/angular";
import type { AtlasHostData } from "@atlas/sdk";
import type { AtlasHostClientEntry } from "@atlas/sdk/lifecycle";
import atlasConfig from "../atlas.config";
import { AppComponent } from "./app.component";

@Component({ selector: "atlas-demo-route-anchor", standalone: true, template: "" })
class DemoRouteAnchorComponent {}

type HostMountRequest = Parameters<AtlasHostClientEntry["mount"]>[0];

export async function bootstrap(request?: HostMountRequest) {
  const root = request ? document.createElement("atlas-host-root") : undefined;
  if (root && request) request.container.append(root);
  const app = await bootstrapApplication(AppComponent, { providers: [provideRouter([{ path: "**", component: DemoRouteAnchorComponent }])] });
  const hostData: AtlasHostData = { hostId: atlasConfig.id, name: atlasConfig.name ?? atlasConfig.id };
  const runtime = await startHost({
    router: app.injector.get(Router),
    location: app.injector.get(Location),
    federation: { initFederation, loadRemoteModule },
    hostData,
    ...(request ? { runtimeConfig: request.runtimeConfig, catalog: request.catalog } : {})
  });
  return { async unmount() { await runtime.stop(); app.destroy(); root?.remove(); } };
}

// examples/hosts/demo-react-host/src/bootstrap.tsx
import 'es-module-shims';
import { StrictMode } from 'react';
import { flushSync } from 'react-dom';
import { createRoot } from 'react-dom/client';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import { initFederation, loadRemoteModule } from '@atlas/sdk/federation';
import type { AtlasHostClientEntry } from '@atlas/sdk/lifecycle';
import {
  AtlasHostProvider,
  AtlasHostLayout,
  AtlasHostStatus,
  AtlasNavigation,
  AtlasRouteOutlet,
  AtlasSlot,
} from '@atlas/runtime/react';
import atlasConfig from '../atlas.config';
import { HostWidgets } from './host-widgets/host-widgets';
import './styles.css';

type HostMountRequest = Parameters<AtlasHostClientEntry['mount']>[0];

function HostLayout() {
  return (
    <AtlasHostLayout layoutId="default">
      <AtlasHostStatus />
      <header>
        <strong>Atlas</strong>
        <AtlasSlot slotId="header" />
      </header>
      <AtlasNavigation aria-label="Application" />
      <HostWidgets />
      <AtlasRouteOutlet />
    </AtlasHostLayout>
  );
}

function mountHost(request: HostMountRequest) {
  const router = createBrowserRouter([{ path: '*', Component: HostLayout }]);
  const element = (
    <StrictMode>
      <AtlasHostProvider
        hostId={atlasConfig.id}
        options={{
          router,
          federation: { initFederation, loadRemoteModule },
          hostData: { hostId: atlasConfig.id, name: atlasConfig.name },
          runtimeConfig: request.runtimeConfig,
          ...(request.catalog ? { catalog: request.catalog } : {}),
        }}
      >
        <RouterProvider router={router} />
      </AtlasHostProvider>
    </StrictMode>
  );
  const root = createRoot(request.container);
  flushSync(() => root.render(element));
  return { unmount: () => root.unmount() };
}

export const mount: AtlasHostClientEntry['mount'] = mountHost;
