// packages/sdk/src/angular/angular-widget/angular-widget.ts
import {
  ApplicationRef,
  Directive,
  DestroyRef,
  effect,
  ElementRef,
  ErrorHandler,
  inject,
  input,
  createComponent,
  type EnvironmentInjector,
  type Signal,
  type Type,
} from '@angular/core';
import type {
  AtlasEventMap,
  AtlasHostDataValue,
  AtlasMountedWidgetHandle,
  AtlasSdk as AtlasSdkValue,
  AtlasWidgetHandle,
  AtlasWidgetLoadingRenderer,
} from '../../host.js';
import { sdkError } from '../../core/sdk-error/sdk-error.js';
import type { AtlasAppAssets } from '../../core/app-assets/app-assets.js';

export interface AngularGetWidgetOptions<TInputs extends object> {
  readonly inputs: TInputs;
  readonly loadingComponent?: Type<unknown>;
}

export interface AngularWidgetBinding<TInputs extends object> {
  readonly widgetId: string;
  readonly inputs: TInputs;
}

export type AngularAtlasSdk<
  THostSdk extends object = {},
  TEvents extends object = AtlasEventMap,
> = Omit<AtlasSdkValue<THostSdk, TEvents>, 'getWidget' | 'hostData'> &
  AtlasAppAssets & {
    /** Live, host-owned data. Call it to read the current immutable snapshot. */
    readonly hostData: Signal<AtlasHostDataValue<THostSdk>>;
    getWidget<TInputs extends object>(
      widgetId: string,
      options: AngularGetWidgetOptions<TInputs>,
    ): AngularWidgetBinding<TInputs>;
  };

interface AngularWidgetRuntime {
  readonly widgetId: string;
  readonly handle: AtlasWidgetHandle<object>;
  readonly loadingComponent?: Type<unknown>;
}

interface ActiveWidget {
  readonly widgetId: string;
  readonly loadingComponent?: Type<unknown>;
  readonly mounted: AtlasMountedWidgetHandle<object>;
}

const widgetRuntimes = new WeakMap<object, AngularWidgetRuntime>();

type WidgetErrorHandler = (error: unknown) => void;

export interface CreateAngularAtlasSdkInput<
  THostSdk extends object,
  TEvents extends object,
> {
  readonly sdk: AtlasSdkValue<THostSdk, TEvents>;
  readonly applicationRef: ApplicationRef;
  readonly environmentInjector: EnvironmentInjector;
  readonly hostData: Signal<AtlasHostDataValue<THostSdk>>;
}

export function createAngularAtlasSdk<
  THostSdk extends object,
  TEvents extends object,
>(
  input: CreateAngularAtlasSdkInput<THostSdk, TEvents>,
): AngularAtlasSdk<THostSdk, TEvents> {
  const { sdk, applicationRef, environmentInjector, hostData } = input;
  const facade = Object.create(sdk) as AngularAtlasSdk<THostSdk, TEvents>;
  Object.defineProperty(facade, 'hostData', { value: hostData });
  Object.defineProperty(facade, 'getWidget', {
    value: <TInputs extends object>(
      widgetId: string,
      options: AngularGetWidgetOptions<TInputs>,
    ): AngularWidgetBinding<TInputs> =>
      createWidgetBinding({
        sdk,
        applicationRef,
        environmentInjector,
        widgetId,
        options,
      }),
  });
  return facade;
}

interface CreateWidgetBindingInput<TInputs extends object> {
  readonly sdk: Pick<AtlasSdkValue, 'getWidget'>;
  readonly applicationRef: ApplicationRef;
  readonly environmentInjector: EnvironmentInjector;
  readonly widgetId: string;
  readonly options: AngularGetWidgetOptions<TInputs>;
}

function createWidgetBinding<TInputs extends object>(
  request: CreateWidgetBindingInput<TInputs>,
): AngularWidgetBinding<TInputs> {
  const { sdk, applicationRef, environmentInjector, widgetId, options } =
    request;
  const renderLoading = options.loadingComponent
    ? createAngularLoadingRenderer({
        loadingComponent: options.loadingComponent,
        applicationRef,
        environmentInjector,
      })
    : undefined;
  const handle = sdk.getWidget<object>(
    widgetId,
    renderLoading ? { renderLoading } : undefined,
  );
  const binding: AngularWidgetBinding<TInputs> = Object.freeze({
    widgetId,
    inputs: options.inputs,
  });
  widgetRuntimes.set(binding, {
    widgetId,
    handle,
    ...(options.loadingComponent
      ? { loadingComponent: options.loadingComponent }
      : {}),
  });

  return binding;
}

@Directive({ selector: '[atlasWidget]', standalone: true })
export class WidgetOutlet<TInputs extends object> {
  readonly atlasWidget = input.required<AngularWidgetBinding<TInputs>>();

  private readonly container =
    inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  private readonly destroyRef = inject(DestroyRef);
  private readonly errorHandler = inject(ErrorHandler);
  private readonly controller = new AngularWidgetOutletController<TInputs>(
    this.container,
    (error) => this.errorHandler.handleError(error),
  );

  constructor() {
    effect(() => {
      void this.controller.render(this.atlasWidget());
    });
    this.destroyRef.onDestroy(() => {
      void this.controller.destroy();
    });
  }
}

export class AngularWidgetOutletController<TInputs extends object> {
  private updateQueue = Promise.resolve();
  private activeWidget: ActiveWidget | undefined;
  private destroyed = false;

  constructor(
    private readonly container: HTMLElement,
    private readonly handleError: WidgetErrorHandler,
  ) {}

  render(binding: AngularWidgetBinding<TInputs>): Promise<void> {
    return this.enqueueUpdate(() => this.applyBinding(binding));
  }

  destroy(): Promise<void> {
    this.destroyed = true;
    return this.enqueueUpdate(() => this.unmountActiveWidget());
  }

  private enqueueUpdate(update: () => Promise<void>): Promise<void> {
    this.updateQueue = this.updateQueue.then(update, update);
    void this.updateQueue.catch(this.handleError);

    return this.updateQueue;
  }

  private async applyBinding(
    binding: AngularWidgetBinding<TInputs>,
  ): Promise<void> {
    if (this.destroyed) return;
    const runtime = readWidgetRuntime(binding);
    const updatableWidget = this.getUpdatableWidget(runtime);
    if (updatableWidget?.setInputs) {
      updatableWidget.setInputs(binding.inputs);
      return;
    }

    await this.unmountActiveWidget();
    if (this.destroyed) return;
    const mounted = await runtime.handle.mount(this.container, binding.inputs);
    if (this.destroyed) {
      await mounted.unmount();
      return;
    }
    this.activeWidget = {
      widgetId: binding.widgetId,
      ...(runtime.loadingComponent
        ? { loadingComponent: runtime.loadingComponent }
        : {}),
      mounted,
    };
  }

  private getUpdatableWidget(
    runtime: AngularWidgetRuntime,
  ): AtlasMountedWidgetHandle<object> | undefined {
    if (this.activeWidget?.widgetId !== runtime.widgetId) return undefined;
    if (this.activeWidget.loadingComponent !== runtime.loadingComponent)
      return undefined;

    return this.activeWidget.mounted;
  }

  private async unmountActiveWidget(): Promise<void> {
    const activeWidget = this.activeWidget;
    this.activeWidget = undefined;
    await activeWidget?.mounted.unmount();
  }
}

function readWidgetRuntime(
  binding: AngularWidgetBinding<object>,
): AngularWidgetRuntime {
  const runtime = widgetRuntimes.get(binding);
  if (runtime) return runtime;

  throw sdkError(
    `Atlas cannot render widget "${binding.widgetId}" because its Angular binding was not created by sdk.getWidget().`,
    {
      suggestedActions:
        'Create the binding with the injected Angular Atlas SDK, then pass it to [atlasWidget].',
      code: 'ATLAS_WIDGET_BINDING_INVALID',
    },
  );
}

function createAngularLoadingRenderer(request: {
  readonly loadingComponent: Type<unknown>;
  readonly applicationRef: ApplicationRef;
  readonly environmentInjector: EnvironmentInjector;
}): AtlasWidgetLoadingRenderer {
  const { loadingComponent, applicationRef, environmentInjector } = request;

  return (container) => {
    const hostElement = container.ownerDocument.createElement('div');
    container.append(hostElement);
    const component = createComponent(loadingComponent, {
      environmentInjector,
      hostElement,
    });
    applicationRef.attachView(component.hostView);
    component.changeDetectorRef.detectChanges();

    return () => {
      applicationRef.detachView(component.hostView);
      component.destroy();
      hostElement.remove();
    };
  };
}

// packages/sdk/src/react/react-widget/react-widget.ts
import {
  Fragment,
  createElement,
  useEffect,
  useRef,
  useState,
  type ComponentType,
  type FunctionComponent,
} from 'react';
import type {
  AtlasEventMap,
  AtlasMountedWidgetHandle,
  AtlasSdk as AtlasSdkValue,
} from './host.js';
import {
  createAtlasAppAssetFacade,
  type AtlasAppAssets,
} from './app-assets.js';
import type { AtlasAppContext } from './lifecycle.js';
import { sdkError } from './sdk-error.js';

export interface ReactGetWidgetOptions {
  loadingComponent?: ComponentType;
}

export type ReactAtlasSdk<
  THostSdk extends object = {},
  TEvents extends object = AtlasEventMap,
> = Omit<AtlasSdkValue<THostSdk, TEvents>, 'getWidget'> &
  AtlasAppAssets & {
    getWidget<TInputs extends object>(
      widgetId: string,
      options?: ReactGetWidgetOptions,
    ): ComponentType<TInputs>;
  };

const sdkFacades = new WeakMap<object, WeakMap<object, object>>();

export function createReactAtlasSdk<
  THostSdk extends object,
  TEvents extends object,
>(
  sdk: AtlasSdkValue<THostSdk, TEvents>,
  context?: AtlasAppContext,
): ReactAtlasSdk<THostSdk, TEvents> {
  const appFacades = sdkFacades.get(sdk) ?? new WeakMap<object, object>();
  sdkFacades.set(sdk, appFacades);
  const facadeContext = context ?? sdk;
  const cached = appFacades.get(facadeContext);
  if (cached) return cached as ReactAtlasSdk<THostSdk, TEvents>;

  const widgets = new Map<
    string,
    Map<ComponentType | undefined, ComponentType<object>>
  >();
  const facade = Object.create(
    context ? createAtlasAppAssetFacade(sdk, context) : sdk,
  ) as ReactAtlasSdk<THostSdk, TEvents>;
  if (!context) {
    Object.defineProperties(facade, {
      assetBaseUrl: { value: unavailableAppAssetUrl },
      assetUrl: { value: unavailableAppAssetUrl },
    });
  }
  Object.defineProperty(facade, 'getWidget', {
    value: <TInputs extends object>(
      widgetId: string,
      options?: ReactGetWidgetOptions,
    ): ComponentType<TInputs> => {
      const loadingComponent = options?.loadingComponent;
      const widgetsByLoadingComponent = widgets.get(widgetId) ?? new Map();
      widgets.set(widgetId, widgetsByLoadingComponent);
      const cachedWidget = widgetsByLoadingComponent.get(loadingComponent);
      if (cachedWidget) return cachedWidget as ComponentType<TInputs>;

      const widget = createWidgetComponent<TInputs>(
        sdk,
        widgetId,
        loadingComponent,
      );
      widgetsByLoadingComponent.set(
        loadingComponent,
        widget as ComponentType<object>,
      );
      return widget;
    },
  });
  appFacades.set(facadeContext, facade);
  return facade;
}

function unavailableAppAssetUrl(): never {
  throw sdkError('App asset URLs require an Atlas app context.', {
    suggestedActions:
      'Call assetBaseUrl() or assetUrl() inside a mounted app. Hosts should use their own asset URLs.',
    code: 'ATLAS_REACT_APP_CONTEXT_MISSING',
  });
}

function createWidgetComponent<TInputs extends object>(
  sdk: Pick<AtlasSdkValue, 'getWidget'>,
  widgetId: string,
  LoadingComponent?: ComponentType,
): FunctionComponent<TInputs> {
  const Widget: FunctionComponent<TInputs> = (inputs) => {
    const container = useRef<HTMLDivElement>(null);
    const mountedWidget = useRef<AtlasMountedWidgetHandle<TInputs> | undefined>(
      undefined,
    );
    const latestInputs = useRef(inputs);
    const [isLoading, setIsLoading] = useState(false);
    latestInputs.current = inputs;

    useEffect(() => {
      const element = container.current;
      if (!element) return;
      let disposed = false;
      const initialInputs = latestInputs.current;
      const renderLoading = LoadingComponent
        ? () => {
            setIsLoading(true);
            return () => {
              if (!disposed) setIsLoading(false);
            };
          }
        : undefined;
      const handle = sdk.getWidget<TInputs>(
        widgetId,
        renderLoading ? { renderLoading } : undefined,
      );
      void handle.mount(element, initialInputs).then((mounted) => {
        if (disposed) {
          void mounted.unmount();
          return;
        }
        mountedWidget.current = mounted;
        if (latestInputs.current !== initialInputs)
          mounted.setInputs?.(latestInputs.current);
      });

      return () => {
        disposed = true;
        const mounted = mountedWidget.current;
        mountedWidget.current = undefined;
        if (mounted) void mounted.unmount();
      };
    }, []);

    useEffect(() => {
      mountedWidget.current?.setInputs?.(inputs);
    }, [inputs]);

    return createElement(
      Fragment,
      undefined,
      isLoading && LoadingComponent
        ? createElement(LoadingComponent, {})
        : undefined,
      createElement('div', {
        ref: container,
        'data-atlas-widget-container': widgetId,
      }),
    );
  };
  Widget.displayName = `AtlasWidget(${widgetId})`;
  return Widget;
}
