// packages/sdk/src/angular-widget.ts
import {
  ApplicationRef,
  createComponent,
  type EnvironmentInjector,
  type Type
} from "@angular/core";
import type {
  AtlasEventMap,
  AtlasMountedWidgetHandle,
  AtlasSdk as AtlasSdkValue,
  AtlasWidgetLoadingRenderer
} from "./host.js";

export interface AngularGetWidgetOptions<TInputs extends object> {
  containerId: string;
  inputs: TInputs;
  loadingComponent?: Type<unknown>;
}

export interface AngularWidgetRef<TInputs extends object> {
  readonly ready: Promise<void>;
  setInputs(inputs: TInputs): void;
  destroy(): Promise<void>;
}

export type AngularAtlasSdk<THostSdk extends object = {}, TEvents extends object = AtlasEventMap> = Omit<AtlasSdkValue<THostSdk, TEvents>, "getWidget"> & {
  getWidget<TInputs extends object>(
    widgetId: string,
    options: AngularGetWidgetOptions<TInputs>
  ): AngularWidgetRef<TInputs>;
};

interface MountAngularWidgetInput<TInputs extends object> {
  sdk: Pick<AtlasSdkValue, "getWidget">;
  applicationRef: ApplicationRef;
  environmentInjector: EnvironmentInjector;
  widgetId: string;
  options: AngularGetWidgetOptions<TInputs>;
}

export function createAngularAtlasSdk<THostSdk extends object, TEvents extends object>(
  sdk: AtlasSdkValue<THostSdk, TEvents>,
  applicationRef: ApplicationRef,
  environmentInjector: EnvironmentInjector
): AngularAtlasSdk<THostSdk, TEvents> {
  const facade = Object.create(sdk) as AngularAtlasSdk<THostSdk, TEvents>;
  Object.defineProperty(facade, "getWidget", {
    value: <TInputs extends object>(
      widgetId: string,
      options: AngularGetWidgetOptions<TInputs>
    ): AngularWidgetRef<TInputs> => mountWidget({ sdk, applicationRef, environmentInjector, widgetId, options })
  });
  return facade;
}

function mountWidget<TInputs extends object>(input: MountAngularWidgetInput<TInputs>): AngularWidgetRef<TInputs> {
  const { sdk, applicationRef, environmentInjector, widgetId, options } = input;
  const container = globalThis.document?.getElementById(options.containerId);
  if (!container) {
    throw new Error(`Atlas widget container "${options.containerId}" was not found. Call getWidget after the container is rendered.`);
  }

  let inputs = options.inputs;
  let mountedWidget: AtlasMountedWidgetHandle<TInputs> | undefined;
  let destroyed = false;
  let destroyPromise: Promise<void> | undefined;
  const renderLoading = options.loadingComponent
    ? createAngularLoadingRenderer(options.loadingComponent, applicationRef, environmentInjector)
    : undefined;
  const handle = sdk.getWidget<TInputs>(widgetId, renderLoading ? { renderLoading } : undefined);
  const mountedWidgetPromise = handle.mount(container, inputs);
  const ready = mountedWidgetPromise.then(async (mounted) => {
    mountedWidget = mounted;
    if (destroyed) {
      await mounted.unmount();
      return;
    }
    if (inputs !== options.inputs) mounted.setInputs?.(inputs);
  });

  return {
    ready,
    setInputs(nextInputs) {
      inputs = nextInputs;
      mountedWidget?.setInputs?.(nextInputs);
    },
    destroy() {
      if (destroyPromise) return destroyPromise;
      destroyed = true;
      destroyPromise = mountedWidget
        ? mountedWidget.unmount()
        : ready;
      return destroyPromise;
    }
  };
}

function createAngularLoadingRenderer(
  loadingComponent: Type<unknown>,
  applicationRef: ApplicationRef,
  environmentInjector: EnvironmentInjector
): AtlasWidgetLoadingRenderer {
  return (container) => {
    const hostElement = container.ownerDocument.createElement("div");
    container.append(hostElement);
    const component = createComponent(loadingComponent, { environmentInjector, hostElement });
    applicationRef.attachView(component.hostView);
    component.changeDetectorRef.detectChanges();
    return () => {
      applicationRef.detachView(component.hostView);
      component.destroy();
      hostElement.remove();
    };
  };
}

// packages/sdk/src/react/react-widget/widget-component.ts
import {
  Fragment,
  createElement,
  useEffect,
  useRef,
  useState,
  type ComponentType,
  type FunctionComponent,
} from 'react';
import type {
  AtlasMountedWidgetHandle,
  AtlasSdk as AtlasSdkValue,
} from '../../host.js';
import { forwardChangedInputs } from './widget-inputs.js';
import { AtlasWidgetMountError } from '../../core/sdk-error/sdk-error.js';

export interface CreateWidgetComponentInput {
  readonly sdk: Pick<AtlasSdkValue, 'getWidget'>;
  readonly widgetId: string;
  readonly loadingComponent: ComponentType | undefined;
}

/** Builds the React component that mounts one host widget into its own container. */
export function createWidgetComponent<TInputs extends object>(
  input: CreateWidgetComponentInput,
): FunctionComponent<TInputs> {
  const { sdk, widgetId, loadingComponent: LoadingComponent } = input;

  const Widget: FunctionComponent<TInputs> = (inputs) => {
    const container = useRef<HTMLDivElement>(null);
    const mountedWidget = useRef<AtlasMountedWidgetHandle<TInputs> | undefined>(
      undefined,
    );
    const latestInputs = useRef(inputs);
    const appliedInputs = useRef<TInputs | undefined>(undefined);
    const [isLoading, setIsLoading] = useState(false);
    const [mountError, setMountError] = useState<unknown>(undefined);
    latestInputs.current = inputs;

    useEffect(() => {
      const element = container.current;

      if (!element) return;

      let disposed = false;
      const initialInputs = latestInputs.current;
      const renderLoading = LoadingComponent
        ? () => {
            setIsLoading(true);

            return () => {
              if (!disposed) setIsLoading(false);
            };
          }
        : undefined;

      const handle = sdk.getWidget<TInputs>(
        widgetId,
        renderLoading ? { renderLoading } : undefined,
      );
      handle.mount(element, initialInputs).then(
        (mounted) => {
          if (disposed) {
            void mounted.unmount();

            return;
          }

          mountedWidget.current = mounted;
          appliedInputs.current = initialInputs;
          forwardChangedInputs(mounted, appliedInputs, latestInputs.current);
        },
        (error: unknown) => {
          if (!disposed)
            setMountError(new AtlasWidgetMountError(widgetId, error));
        },
      );

      return () => {
        disposed = true;
        const mounted = mountedWidget.current;
        mountedWidget.current = undefined;

        if (mounted) void mounted.unmount();
      };
    }, []);

    useEffect(() => {
      const mounted = mountedWidget.current;

      if (mounted) forwardChangedInputs(mounted, appliedInputs, inputs);
    }, [inputs]);

    if (mountError !== undefined) throw mountError;

    return createElement(
      Fragment,
      undefined,
      isLoading && LoadingComponent
        ? createElement(LoadingComponent, {})
        : undefined,
      createElement('div', {
        ref: container,
        'data-atlas-widget-container': widgetId,
      }),
    );
  };
  Widget.displayName = `AtlasWidget(${widgetId})`;

  return Widget;
}
