// examples/hosts/demo-react-host/src/host-widgets/host-widgets.tsx
import { useState } from 'react';
import { useAtlasSdk } from '@atlas/sdk/react';

export function HostWidgets() {
  const atlas = useAtlasSdk();
  const [showReact, setShowReact] = useState(false);
  const [showAngular, setShowAngular] = useState(false);
  const [count, setCount] = useState(12);
  const [status, setStatus] = useState('pending');
  const ProductCount = atlas.getWidget<{ count: number }>(
    '6f4994c1-b95f-4b24-a01a-106dd61aa4fb',
  );
  const OrderStatus = atlas.getWidget<{ status: string }>(
    '98abc74d-a11f-4eca-8255-c6f2f49e3d6e',
  );

  return (
    <section aria-label="Host widgets">
      <h2>Host widgets</h2>
      <button onClick={() => setShowReact(!showReact)}>
        {showReact ? 'Hide React widget' : 'Show React widget'}
      </button>
      <button onClick={() => setCount(24)}>Update React widget</button>
      <button onClick={() => setShowAngular(!showAngular)}>
        {showAngular ? 'Hide Angular widget' : 'Show Angular widget'}
      </button>
      <button onClick={() => setStatus('paid')}>Update Angular widget</button>
      {showReact && (
        <section aria-label="React widget">
          <ProductCount count={count} />
        </section>
      )}
      {showAngular && (
        <section aria-label="Angular widget">
          <OrderStatus status={status} />
        </section>
      )}
    </section>
  );
}

// examples/hosts/demo-angular-host/src/host-widgets/host-widgets.ts
import { Component, signal } from '@angular/core';
import { injectAtlasSdk, WidgetOutlet } from '@atlas/sdk/angular';

@Component({
  selector: 'atlas-host-widgets',
  standalone: true,
  imports: [WidgetOutlet],
  template: `
    <section aria-label="Host widgets">
      <h2>Host widgets</h2>
      <button (click)="showReact.set(!showReact())">
        {{ showReact() ? 'Hide React widget' : 'Show React widget' }}
      </button>
      <button (click)="updateReactWidget()">Update React widget</button>
      <button (click)="showAngular.set(!showAngular())">
        {{ showAngular() ? 'Hide Angular widget' : 'Show Angular widget' }}
      </button>
      <button (click)="updateAngularWidget()">Update Angular widget</button>
      @if (showReact()) {
        <section
          aria-label="React widget"
          [atlasWidget]="reactWidget()"
        ></section>
      }
      @if (showAngular()) {
        <section
          aria-label="Angular widget"
          [atlasWidget]="angularWidget()"
        ></section>
      }
    </section>
  `,
})
export class HostWidgets {
  private readonly atlas = injectAtlasSdk();
  readonly showReact = signal(false);
  readonly showAngular = signal(false);
  readonly reactWidget = signal(
    this.atlas.getWidget('6f4994c1-b95f-4b24-a01a-106dd61aa4fb', {
      inputs: { count: 12 },
    }),
  );
  readonly angularWidget = signal(
    this.atlas.getWidget('98abc74d-a11f-4eca-8255-c6f2f49e3d6e', {
      inputs: { status: 'pending' },
    }),
  );

  updateReactWidget(): void {
    this.reactWidget.set(
      this.atlas.getWidget('6f4994c1-b95f-4b24-a01a-106dd61aa4fb', {
        inputs: { count: 24 },
      }),
    );
  }

  updateAngularWidget(): void {
    this.angularWidget.set(
      this.atlas.getWidget('98abc74d-a11f-4eca-8255-c6f2f49e3d6e', {
        inputs: { status: 'paid' },
      }),
    );
  }
}
