// packages/generators/src/angular/host/angular-host-generator.ts
import type { AngularVersionProfile } from '../../shared/versions/generator-versions.js';

export function angularHostComponent(): string {
  return `import { Component } from "@angular/core";
import { RouterOutlet } from "@angular/router";
import { AtlasHostLayout, AtlasHostStatus, AtlasNavigation, AtlasRouteOutlet, AtlasSlot } from "@atlas/runtime/angular";

@Component({
  selector: "atlas-host-root",
  standalone: true,
  imports: [RouterOutlet, AtlasHostLayout, AtlasHostStatus, AtlasNavigation, AtlasRouteOutlet, AtlasSlot],
  template: \`
    <ng-container *atlasHostLayout="'default'">
      <atlas-host-status />
      <header>
        <strong>Atlas</strong>
        <atlas-slot slotId="header" />
      </header>
      <atlas-navigation aria-label="Application" />
      <atlas-route-outlet />
    </ng-container>
    <router-outlet hidden />
  \`
})
export class AppComponent {}
`;
}

export function angularHostMain(): string {
  return `const root = document.querySelector("atlas-host-root");
if (!root) throw new Error("Atlas host root is missing.");

root.textContent = "Start this Atlas host with atlas dev.";
`;
}

export function angularHostRoutes(): string {
  return `import { Routes } from "@angular/router";
import { AtlasDefaultHostRouteComponent } from "@atlas/runtime/angular";

export const routes: Routes = [
  { path: "**", component: AtlasDefaultHostRouteComponent }
];
`;
}

export function angularHostAppConfig(profile: AngularVersionProfile): string {
  const zonelessProvider = profile.requiresZonelessProvider
    ? 'import { ApplicationConfig, provideZonelessChangeDetection } from "@angular/core";\n'
    : 'import { ApplicationConfig } from "@angular/core";\n';
  const providers = profile.requiresZonelessProvider
    ? 'provideZonelessChangeDetection(),\n    provideRouter(routes)'
    : 'provideRouter(routes)';
  return `${zonelessProvider}import { provideRouter } from "@angular/router";
import { routes } from "./app.routes";

export const appConfig: ApplicationConfig = {
  providers: [
    ${providers}
  ]
};
`;
}

export function angularHostSdkConfig(): string {
  return `import type { Injector } from "@angular/core";
import type { HostSdkOptions } from "@atlas/runtime/angular";

/** Add product-specific host SDK capabilities here. */
interface CustomerHostSdk {}

export function createCustomHostSdkOptions(
  _injector: Injector,
): HostSdkOptions<CustomerHostSdk> {
  return {};
}
`;
}

export function angularHostBootstrap(): string {
  return `import { Location } from "@angular/common";
import { Router } from "@angular/router";
import { initFederation, loadRemoteModule } from "@atlas/sdk/federation";
import type { AtlasHostClientEntry } from "@atlas/sdk/lifecycle";
import { AtlasAngularHostAnchors, bootstrapAngularHost } from "@atlas/runtime/angular";
import atlasConfig from "../atlas.config";
import { appConfig } from "./app/app.config";
import { AppComponent } from "./app/app.component";
import { createCustomHostSdkOptions } from "./app/host.config";

type HostMountRequest = Parameters<AtlasHostClientEntry["mount"]>[0];

export async function bootstrap(request: HostMountRequest) {
  return bootstrapAngularHost({
    component: AppComponent,
    appConfig,
    request,
    createHostOptions: (injector) => ({
      router: injector.get(Router),
      location: injector.get(Location),
      anchors: injector.get(AtlasAngularHostAnchors),
      federation: { initFederation, loadRemoteModule },
      hostData: { hostId: atlasConfig.id, name: atlasConfig.name },
      ...createCustomHostSdkOptions(injector),
      runtimeConfig: request.runtimeConfig,
      ...(request.catalog ? { catalog: request.catalog } : {})
    })
  });
}

export const mount: AtlasHostClientEntry["mount"] = bootstrap;
`;
}

// packages/generators/src/react/host/react-host-generator.ts
import type { ReactVersionProfile } from '../../shared/versions/generator-versions.js';

export function reactHostBootstrap(profile: ReactVersionProfile): string {
  const imports =
    profile.major === 17
      ? 'import { render, unmountComponentAtNode } from "react-dom";'
      : 'import { flushSync } from "react-dom";\nimport { createRoot } from "react-dom/client";';
  const renderHost =
    profile.major === 17
      ? 'render(element, container);\n  return { unmount: () => unmountComponentAtNode(container) };'
      : 'const root = createRoot(container);\n  flushSync(() => root.render(element));\n  return { unmount: () => root.unmount() };';
  return `import "es-module-shims";
import { StrictMode } from "react";
${imports}
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import { initFederation, loadRemoteModule } from "@atlas/sdk/federation";
import type { AtlasHostClientEntry } from "@atlas/sdk/lifecycle";
import {
  AtlasHostProvider,
  AtlasHostStatus,
  AtlasHostLayout,
  AtlasNavigation,
  AtlasRouteOutlet,
  AtlasSlot
} from "@atlas/runtime/react";
import atlasConfig from "../atlas.config";
import { useCustomHostSdkOptions, type CustomerHostSdk } from "./host.config";
import "./styles.css";

type HostMountRequest = Parameters<AtlasHostClientEntry["mount"]>[0];

function HostLayout() {
  return (
    <AtlasHostLayout layoutId="default">
      <AtlasHostStatus />
      <header>
        <strong>Atlas</strong>
        <AtlasSlot slotId="header" />
      </header>
      <AtlasNavigation aria-label="Application" />
      <AtlasRouteOutlet />
    </AtlasHostLayout>
  );
}

function HostApplication({ request, router }: { request: HostMountRequest; router: ReturnType<typeof createBrowserRouter> }) {
  const { hostData, ...sdkOptions } = useCustomHostSdkOptions();

  return (
    <AtlasHostProvider<CustomerHostSdk>
        hostId={atlasConfig.id}
        options={{
          router,
          federation: { initFederation, loadRemoteModule },
          hostData: { hostId: atlasConfig.id, name: atlasConfig.name, ...hostData },
          ...sdkOptions,
          runtimeConfig: request.runtimeConfig,
          ...(request.catalog ? { catalog: request.catalog } : {})
        }}
      >
        <RouterProvider router={router} />
    </AtlasHostProvider>
  );
}

function mountHost(request: HostMountRequest) {
  const router = createBrowserRouter([{ path: "*", Component: HostLayout }]);
  const element = (
    <StrictMode>
      <HostApplication request={request} router={router} />
    </StrictMode>
  );
  const container = request.container;
  ${renderHost}
};

export const mount: AtlasHostClientEntry["mount"] = mountHost;
`;
}

export function reactHostSdkConfig(): string {
  return `import type { HostSdkOptions } from "@atlas/runtime/react";

/** Add product-specific host SDK capabilities here. Hooks are supported. */
export interface CustomerHostSdk {}

export function useCustomHostSdkOptions(): HostSdkOptions<CustomerHostSdk> {
  return {};
}
`;
}

export function reactHostMain(): string {
  return `const root = document.getElementById("root");
if (!root) throw new Error("React root is missing.");

root.textContent = "Start this Atlas host with atlas dev.";
`;
}
