// examples/mfs/dashboard-angular/src/entry.ts
import "zone.js";
import { Component, InjectionToken, inject } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import { defineMicrofrontend, injectAtlasSdk, provideAtlasSdk } from "@atlas/sdk/angular";
import type { AtlasMfContext } from "@atlas/sdk/lifecycle";

export const ATLAS_MF_CONTEXT = new InjectionToken<AtlasMfContext>("ATLAS_MF_CONTEXT");

interface HostExtensions {
  hostData: { projectId: string };
  httpClient: typeof fetch;
}

@Component({ selector: "atlas-dashboard-angular-root", standalone: true, template: `<h1>Dashboard Angular</h1><p>Mounted at {{ context.basePath }}</p><button type="button" (click)="showToast()">Show toast</button><button type="button" (click)="openReactPopup()">Open React widget popup</button>` })
class AtlasMfRootComponent {
  readonly context = inject(ATLAS_MF_CONTEXT);
  private readonly atlas = injectAtlasSdk<HostExtensions>();
  showToast() { this.atlas.toast.open({ title: `Project ${this.atlas.hostData.projectId} is ready` }); }
  openReactPopup() { this.atlas.popup.open({ title: "Product count", content: { widget: "catalog-react/product-count", props: { count: 42, label: "Products in popup" } }, draggable: true, resizable: true }); }
}

export default defineMicrofrontend(async ({ container, sdk, context }) => {
  const element = document.createElement("atlas-dashboard-angular-root");
  const widgetContainer = document.createElement("section");
  widgetContainer.setAttribute("aria-label", "Shared React product count");
  container.append(element);
  container.append(widgetContainer);
  const app = await bootstrapApplication(AtlasMfRootComponent, { providers: [provideAtlasSdk(sdk), { provide: ATLAS_MF_CONTEXT, useValue: context }] });
  context.loading.show();
  const widget = await context.widgets.mount("catalog-react/product-count", widgetContainer, { count: 24, label: "React products" });
  context.ready();
  return { async unmount() { await widget.unmount(); app.destroy(); element.remove(); widgetContainer.remove(); } };
});

// examples/mfs/dashboard-react/src/entry.tsx
import { createElement, useEffect, useRef } from "react";
import { createRoot } from "react-dom/client";
import { defineMicrofrontend, useAtlasSdk } from "@atlas/sdk/react";
import type { AtlasMfMountRequest } from "@atlas/sdk/lifecycle";
import "./styles.css";

if (import.meta.hot) await import("@vitejs/plugin-react/preamble");

interface HostExtensions {
  hostData: { projectId: string };
  httpClient: typeof fetch;
}

function App({ context }: AtlasMfMountRequest) {
  const atlas = useAtlasSdk<HostExtensions>();
  const widget = useRef<HTMLDivElement>(null);
  useEffect(() => {
    let disposed = false;
    let unmount: () => Promise<void> = async () => undefined;
    context.loading.show();
    void context.widgets.mount("orders-angular/order-status", widget.current!, { status: "paid" }).then((mounted) => {
      if (disposed) return mounted.unmount();
      unmount = mounted.unmount;
      context.ready();
    });
    return () => { disposed = true; void unmount(); };
  }, [context]);
  return <section><h1>Dashboard React</h1><p>Project {atlas.hostData.projectId} mounted at {context.basePath}</p><div ref={widget} /><button type="button" onClick={() => atlas.toast.open({ title: "Dashboard React is ready" })}>Show toast</button><button type="button" onClick={() => atlas.popup.open({ title: "Order status", content: { widget: "orders-angular/order-status", props: { status: "processing" } }, draggable: true, resizable: true })}>Open Angular widget popup</button></section>;
}

export default defineMicrofrontend({ createRoot, createElement: (request) => createElement(App, request) });
