// packages/runtime/src/adapters/angular-host-ui.driver.ts
import '@angular/compiler';
import { jest } from '@jest/globals';
import {
  Component,
  Input,
  provideZonelessChangeDetection,
  type ApplicationRef,
} from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { anAppManifest, aRoutePlacement } from '@atlas/testkit';
import type { DomHostUiRenderers } from '../dom-host/dom-host.types.js';
import type { DisposeRenderer } from '../widget-loader/widget-loader.types.js';
import { createAngularHostUiRenderers } from './angular-host-ui.js';
import type { AngularHostUiComponents } from './angular-host-ui.types.js';

@Component({ selector: 'atlas-test-root', standalone: true, template: '' })
class TestRoot {}

@Component({
  selector: 'atlas-test-loading',
  standalone: true,
  template: '<p data-testid="loading"></p>',
})
export class TestLoading {}

@Component({
  selector: 'atlas-test-error',
  standalone: true,
  template:
    '<button data-testid="retry" (click)="retry()">{{ error.message }}</button>',
})
export class TestError {
  @Input({ required: true }) error!: Error;
  @Input({ required: true }) retry!: () => void;
}

export class AngularHostUiDriver {
  private readonly status = document.createElement('div');
  private readonly retry = jest.fn<() => void>();
  private components: AngularHostUiComponents = {};
  private renderers: DomHostUiRenderers = {};
  private app: ApplicationRef | undefined;
  private dispose: DisposeRenderer | undefined;

  constructor() {
    document.body.replaceChildren(
      document.createElement('atlas-test-root'),
      this.status,
    );
  }

  readonly given = {
    components: (components: AngularHostUiComponents) => {
      this.components = components;

      return this;
    },
  };

  readonly when = {
    bootstrapped: async () => {
      this.app = await bootstrapApplication(TestRoot, {
        providers: [provideZonelessChangeDetection()],
      });
      this.renderers = createAngularHostUiRenderers({
        components: this.components,
        applicationRef: this.app,
      });
    },
    loadingRendered: () => {
      this.dispose = this.renderers.renderLoading?.(this.status, {
        manifest: anAppManifest(),
        placement: aRoutePlacement(),
        container: this.status,
        state: 'loading',
      });
    },
    hostErrorRendered: (error: Error) => {
      this.dispose = this.renderers.renderHostError?.(
        this.status,
        error,
        this.retry,
      );
    },
    retryClicked: () =>
      this.status
        .querySelector<HTMLButtonElement>('[data-testid="retry"]')!
        .click(),
    disposed: () => this.dispose?.(),
  };

  readonly get = {
    renderers: () => this.renderers,
    statusText: () => this.status.textContent,
    loadingPresent: () =>
      this.status.querySelector('[data-testid="loading"]') !== null,
    childCount: () => this.status.childElementCount,
    retryMock: () => this.retry,
    attachedViews: () => this.app!.viewCount,
  };
}

// packages/runtime/src/adapters/react-host-ui.driver.tsx
import { jest } from '@jest/globals';
import { faker } from '@faker-js/faker';
import { act, render } from '@testing-library/react';
import { createContext, createElement, useContext } from 'react';
import { anAppManifest, aRoutePlacement } from '@atlas/testkit';
import type { AtlasHostMountEvent } from '../host-runtime/host-runtime.types.js';
import type { DisposeRenderer } from '../widget-loader/widget-loader.types.js';
import type { AtlasErrorProps, AtlasHostComponents } from '../react.types.js';
import {
  AtlasHostUiPortals,
  createHostUiStore,
  createReactHostUiRenderers,
} from './react-host-ui.js';
import type {
  HostUiErrorKind,
  HostUiLoadingKind,
} from './react-host-ui.types.js';

const ThemeContext = createContext('');

function kindView(kind: HostUiLoadingKind) {
  return function LoadingView() {
    return createElement(
      'output',
      { 'data-testid': kind },
      useContext(ThemeContext),
    );
  };
}

function errorView(kind: HostUiErrorKind) {
  return function ErrorView(props: AtlasErrorProps) {
    return createElement(
      'button',
      { 'data-testid': kind, type: 'button', onClick: props.retry },
      props.error.message,
    );
  };
}

const COMPONENTS: AtlasHostComponents = {
  loading: kindView('loading'),
  widgetLoading: kindView('widgetLoading'),
  error: errorView('error'),
  widgetError: errorView('widgetError'),
  hostError: errorView('hostError'),
};

export class ReactHostUiDriver {
  private readonly status = document.createElement('div');
  private readonly retry = jest.fn<() => void>();
  private readonly store = createHostUiStore();
  private readonly renderers = createReactHostUiRenderers({
    store: this.store,
    components: COMPONENTS,
  });
  private theme = faker.word.noun();
  private dispose: DisposeRenderer | void = undefined;

  readonly given = {
    theme: (theme: string) => {
      this.theme = theme;

      return this;
    },
  };

  readonly when = {
    rendered: () => {
      render(
        createElement(
          ThemeContext.Provider,
          { value: this.theme },
          createElement(AtlasHostUiPortals, {
            store: this.store,
            components: COMPONENTS,
          }),
        ),
      );
    },
    loadingStatusShown: (kind: HostUiLoadingKind) =>
      act(() => {
        const show = {
          loading: () =>
            this.renderers.renderLoading!(this.status, this.mountEvent()),
          widgetLoading: () =>
            this.renderers.renderWidgetLoading!(this.status, {
              widgetId: faker.string.uuid(),
            }),
        };

        this.dispose = show[kind]();
      }),
    errorStatusShown: (kind: HostUiErrorKind, error: Error) =>
      act(() => {
        const show = {
          error: () =>
            this.renderers.renderError!(
              this.status,
              { ...this.mountEvent(), error },
              this.retry,
            ),
          widgetError: () =>
            this.renderers.renderWidgetError!(
              this.status,
              { widgetId: faker.string.uuid(), error },
              this.retry,
            ),
          hostError: () =>
            this.renderers.renderHostError!(this.status, error, this.retry),
        };

        this.dispose = show[kind]();
      }),
    statusDisposed: () =>
      act(() => {
        this.dispose?.();
      }),
    retryClicked: () =>
      act(() => {
        this.status.querySelector('button')!.click();
      }),
  };

  readonly get = {
    status: () => this.status,
    rendered: (kind: HostUiLoadingKind | HostUiErrorKind) =>
      this.status.querySelector(`[data-testid="${kind}"]`),
    retryMock: () => this.retry,
  };

  private mountEvent(): AtlasHostMountEvent {
    return {
      manifest: anAppManifest(),
      placement: aRoutePlacement(),
      container: document.createElement('div'),
      state: 'loading',
    };
  }
}
