// examples/apps/dashboard-angular/src/entry.ts
import "zone.js";
import { Component, inject } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import { defineApp, injectAtlasAppContext, injectAtlasSdk, provideAtlasAppContext, provideAtlasSdk } from "@atlas/sdk/angular";

@Component({ selector: "atlas-dashboard-angular-root", standalone: true, template: `<h1>Dashboard Angular</h1><p>Mounted at {{ context.basePath }}</p><button type="button" (click)="showToast()">Show toast</button><button type="button" (click)="openReactPopup()">Open React widget popup</button>` })
class AtlasAppRootComponent {
  readonly context = injectAtlasAppContext();
  private readonly atlas = injectAtlasSdk();
  showToast() { this.atlas.toast.open({ title: `${this.atlas.hostData.name} is ready` }); }
  openReactPopup() { this.atlas.popup.open({ title: "Product count", content: { widget: "catalog-react/product-count", props: { count: 42, label: "Products in popup" } }, draggable: true, resizable: true }); }
}

export default defineApp(async ({ container, sdk, context }) => {
  const element = document.createElement("atlas-dashboard-angular-root");
  const widgetContainer = document.createElement("section");
  widgetContainer.setAttribute("aria-label", "Shared React product count");
  container.append(element);
  container.append(widgetContainer);
  const appLoaded = context.loading.waitUntilReady();
  const app = await bootstrapApplication(AtlasAppRootComponent, { providers: [provideAtlasAppContext(context), provideAtlasSdk(sdk)] });
  context.loading.show();
  const widget = await context.widgets.mount("catalog-react/product-count", widgetContainer, { count: 24, label: "React products" });
  appLoaded();
  return { async unmount() { await widget.unmount(); app.destroy(); element.remove(); widgetContainer.remove(); } };
});

// examples/apps/dashboard-react/src/entry.tsx
import { createElement, useEffect, useRef } from "react";
import { createRoot } from "react-dom/client";
import { defineApp, useAppLoaded, useAtlasSdk } from "@atlas/sdk/react";
import type { AtlasAppMountRequest } from "@atlas/sdk/lifecycle";
import "./styles.css";

function App({ context }: AtlasAppMountRequest) {
  const atlas = useAtlasSdk();
  const appLoaded = useAppLoaded();
  const widget = useRef<HTMLDivElement>(null);
  useEffect(() => {
    let disposed = false;
    let unmount: () => Promise<void> = async () => undefined;
    context.loading.show();
    void context.widgets.mount("orders-angular/order-status", widget.current!, { status: "paid" }).then((mounted) => {
      if (disposed) return mounted.unmount();
      unmount = mounted.unmount;
      appLoaded();
    });
    return () => { disposed = true; void unmount(); };
  }, [appLoaded, context]);
  return <section><h1>Dashboard React</h1><p>{atlas.hostData.name} mounted at {context.basePath}</p><div ref={widget} /><button type="button" onClick={() => atlas.toast.open({ title: "Dashboard React is ready" })}>Show toast</button><button type="button" onClick={() => atlas.popup.open({ title: "Order status", content: { widget: "orders-angular/order-status", props: { status: "processing" } }, draggable: true, resizable: true })}>Open Angular widget popup</button></section>;
}

export default defineApp({ createRoot, createElement: (request) => createElement(App, request) });
