// packages/generators/src/react/host/react-host-generator.specs.ts
import { aReactVersionProfile } from '../../testkit/version-profiles.testkit.js';
import { ReactHostGeneratorDriver } from './react-host-generator.driver.js';

describe('renderReactHostBootstrap', () => {
  let driver: ReactHostGeneratorDriver;

  beforeEach(() => {
    driver = new ReactHostGeneratorDriver();
  });

  describe('when major is 18 or above', () => {
    beforeEach(() => {
      driver.given
        .profile(aReactVersionProfile({ major: 18 }))
        .when.bootstrapGenerated();
    });

    it('should import createRoot from the react dom client when generated', () => {
      expect(driver.get.contents()).toContain(
        'import { createRoot } from "react-dom/client";',
      );
    });

    it('should pass createRoot as the react dom renderer when generated', () => {
      expect(driver.get.contents()).toContain('  reactDom: { createRoot },');
    });
  });

  describe('when major is 17 or below', () => {
    beforeEach(() => {
      driver.given
        .profile(aReactVersionProfile({ major: 17 }))
        .when.bootstrapGenerated();
    });

    it('should import legacy render and unmount when generated', () => {
      expect(driver.get.contents()).toContain(
        'import { render, unmountComponentAtNode } from "react-dom";',
      );
    });

    it('should pass legacy render and unmount as the react dom renderer when generated', () => {
      expect(driver.get.contents()).toContain(
        '  reactDom: { render, unmountComponentAtNode },',
      );
    });
  });

  describe('when generated', () => {
    beforeEach(() => {
      driver.when.bootstrapGenerated();
    });

    it('should export mount defined from the atlas config and host layout when generated', () => {
      expect(driver.get.contents())
        .toContain(`export const mount = defineReactHost<CustomerHostSdk>({
  config: atlasConfig,
  layout: HostLayout,`);
    });

    it('should pass the host providers and custom sdk options hook when generated', () => {
      expect(driver.get.contents()).toContain(`  providers: HostProviders,
  useSdkOptions: useCustomHostSdkOptions
});`);
    });
  });
});

describe('renderReactHostLayout', () => {
  let driver: ReactHostGeneratorDriver;

  beforeEach(() => {
    driver = new ReactHostGeneratorDriver();
  });

  it('should render the atlas host layout with status, header slot, navigation and route outlet when generated', () => {
    driver.when.layoutGenerated();

    expect(driver.get.contents())
      .toContain(`    <AtlasHostLayout layoutId="default">
      <AtlasHostStatus />
      <header>
        <strong>Atlas</strong>
        <AtlasSlot slotId="header" />
      </header>
      <AtlasNavigation aria-label="Application" />
      <AtlasRouteOutlet />
    </AtlasHostLayout>`);
  });
});

describe('renderReactHostSdkConfig', () => {
  let driver: ReactHostGeneratorDriver;

  beforeEach(() => {
    driver = new ReactHostGeneratorDriver();
  });

  it('should export host providers wrapping children in strict mode when generated', () => {
    driver.when.sdkConfigGenerated();

    expect(driver.get.contents())
      .toContain(`export function HostProviders({ children }: { children?: ReactNode }) {
  return <StrictMode>{children}</StrictMode>;
}`);
  });

  it('should export an empty custom host sdk options hook when generated', () => {
    driver.when.sdkConfigGenerated();

    expect(driver.get.contents())
      .toContain(`export function useCustomHostSdkOptions(): HostSdkOptions<CustomerHostSdk> {
  return {};
}`);
  });
});

describe('renderReactHostMain', () => {
  let driver: ReactHostGeneratorDriver;

  beforeEach(() => {
    driver = new ReactHostGeneratorDriver();
  });

  it('should write the atlas dev placeholder into the root element when generated', () => {
    driver.when.mainGenerated();

    expect(driver.get.contents())
      .toBe(`const root = document.getElementById("root");
if (!root) throw new Error("React root is missing.");

root.textContent = "Start this Atlas host with atlas dev.";
`);
  });
});

// packages/generators/src/angular/host/angular-host-generator.specs.ts
import { AngularHostGeneratorDriver } from './angular-host-generator.driver.js';

describe('renderAngularHostAppConfig', () => {
  let driver: AngularHostGeneratorDriver;

  beforeEach(() => {
    driver = new AngularHostGeneratorDriver();
  });

  it('should provide no providers when no zoneless provider is required', () => {
    driver.given.requiresZonelessProvider(false).when.appConfigGenerated();

    expect(driver.get.contents())
      .toBe(`import { ApplicationConfig } from "@angular/core";

export const appConfig: ApplicationConfig = {
  providers: []
};
`);
  });

  it('should provide zoneless change detection when a zoneless provider is required', () => {
    driver.given.requiresZonelessProvider(true).when.appConfigGenerated();

    expect(driver.get.contents())
      .toBe(`import { ApplicationConfig, provideZonelessChangeDetection } from "@angular/core";

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection()
  ]
};
`);
  });
});

describe('renderAngularHostComponent', () => {
  let driver: AngularHostGeneratorDriver;

  beforeEach(() => {
    driver = new AngularHostGeneratorDriver();
  });

  it('should render the atlas host layout with status, header slot, navigation and route outlet when generated', () => {
    driver.when.componentGenerated();

    expect(driver.get.contents())
      .toContain(`    <ng-container *atlasHostLayout="'default'">
      <atlas-host-status />
      <header>
        <strong>Atlas</strong>
        <atlas-slot slotId="header" />
      </header>
      <atlas-navigation aria-label="Application" />
      <atlas-route-outlet />
    </ng-container>
    <router-outlet hidden />`);
  });
});

describe('renderAngularHostMain', () => {
  let driver: AngularHostGeneratorDriver;

  beforeEach(() => {
    driver = new AngularHostGeneratorDriver();
  });

  it('should write the atlas dev placeholder into the host root when generated', () => {
    driver.when.mainGenerated();

    expect(driver.get.contents())
      .toBe(`const root = document.querySelector("atlas-host-root");
if (!root) throw new Error("Atlas host root is missing.");

root.textContent = "Start this Atlas host with atlas dev.";
`);
  });
});

describe('renderAngularHostSdkConfig', () => {
  let driver: AngularHostGeneratorDriver;

  beforeEach(() => {
    driver = new AngularHostGeneratorDriver();
  });

  it('should export the customer host sdk type when generated', () => {
    driver.when.sdkConfigGenerated();

    expect(driver.get.contents()).toContain(
      'export interface CustomerHostSdk {}',
    );
  });

  it('should export an empty custom host sdk options factory when generated', () => {
    driver.when.sdkConfigGenerated();

    expect(driver.get.contents())
      .toContain(`export function createCustomHostSdkOptions(
  _injector: Injector,
): HostSdkOptions<CustomerHostSdk> {
  return {};
}`);
  });
});

describe('renderAngularHostBootstrap', () => {
  let driver: AngularHostGeneratorDriver;

  beforeEach(() => {
    driver = new AngularHostGeneratorDriver();
  });

  it('should export mount defined from the atlas config, component, app config and custom sdk options when generated', () => {
    driver.when.bootstrapGenerated();

    expect(driver.get.contents())
      .toBe(`import { defineAngularHost } from "@atlas/runtime/angular";
import atlasConfig from "../atlas.config";
import { appConfig } from "./app/app.config";
import { AppComponent } from "./app/app.component";
import { createCustomHostSdkOptions, type CustomerHostSdk } from "./app/host.config";

export const mount = defineAngularHost<CustomerHostSdk>({
  config: atlasConfig,
  component: AppComponent,
  appConfig,
  sdkOptions: createCustomHostSdkOptions
});
`);
  });
});
